app-vol:
  image: busybox
  container_name: app-vol
  volumes:
    - '/apps/google-config:/.config'
    - '/apps/supervisor-config/base:/supervisor'
    - '/apps/supervisor-config/apps:/etc/supervisor/conf.d'
    - '/apps/cron-config:/.cron-config'
    - '/apps/webapp:/var/www/html'
  command: tail -f /dev/null
app:
  build: .
  container_name: app
  volumes_from:
    - app-vol
  ports:
    - "80:80"
